<!DOCTYPE html>
<html lang="es-co">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="description" content="SSMAGAS:autopartes para la conversion de gasolina a gas natural" />
    <meta name="keywords" content="rocores, contenedores, gas natural vehicular, gnv, glp, accesorios" />
    <meta name="author" content="MohanSoft" />
    <link rel="shortcut icon" type="image/x-icon" href="icon.ico">
    <title>Pedreros Orozco & Cia.</title>


    <!--Estilos-->
    <link href="Estilos/normalize.css" rel="stylesheet" />
    <link href="Estilos/default.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Economica' rel='stylesheet' type='text/css'>
    <!--/Estilos-->
    <!--Script-->
    <script src="Scripts/modernizr.custom.28468.js"></script>
    <!--/Script-->

</head>

<body>

    <nav id="menu-principal" class="menu-principal" role="navigation">
            
            <ul>
                <li onclick="inicio()">Inicio </li>
                <li>
                    <a href="#">Empresa</a>
                    <div class="submenu">
                        <div class="submenu-interno">
                            <div>
                                <a href="?pagina=empresa">
                                    <h4>Historia</h4>
                                </a>
                                <ul>
                                    <li>
                                        <p>
                                            SSMGAS fundada el 11 de febrero de 1991 es una compañía la cual presta el servicio de suministro de la 
                                            línea de mezcladores, racores y accesorios a la industria del GNV y GLP en general.
                                        </p>
                                    </li>
                                </ul>
                            </div>
                            <div>
                                <a href="?pagina=empresa">
                                    <h4>Misión & Visión</h4>
                                </a>
                                <ul>
                                    <li>
                                        <p>
                                            SSMGAS para el 2017 se consolidara como la empresa líder 
                                            en el mercado nacional de productos para la industria automotriz y domiciliario del GNV y GLP.
                                        </p>

                                    </li>
                                </ul>
                            </div>
                            <div>
                                <a href="?pagina=empresa">
                                    <h4>Certificacion & Respaldo</h4>
                                </a>
                                <ul>
                                    <li>
                                        <p>
                                            Con una politica de calidad bien planteada y ejecutada hemos logrado obtener las mas
                                            altas certificaciones internacionales de claidad en mas de 30 referecnicas de nuestros 
                                            productos, brindando seguridad y respaldo a nuestros clientes.
                                        </p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- /submenu-interno -->
                    </div>
                    <!-- /submenu -->
                </li>
                <li>
                    <a href="?pagina=productos">Productos</a>
                    <div class="submenu">
                        <div class="submenu-interno" id="submenu-pruductos">
                            <div>
                                <h4>Mezcladores</h4>
                                <ul>
                                    <li><a href="?pagina=mezcladores">Amplia gama de mezcladores para todas las marcas y modelos de automovil</a></li>
                                    
                                    <li><a href="?pagina=mezcladores">Ver mas....</a></li>
                                </ul>
                            </div>
                            <div>
                                <h4>Accesorios</h4>
                                <ul>
                                    <li><a href="?pagina=productos">Racores</a></li>
                                    <li><a href="?pagina=productos">Tees</a></li>
                                    <li><a href="?pagina=productos">Boquillas</a></li>
                                    <li><a href="?pagina=productos">Ver mas....</a></li>
                                </ul>
                            </div>
                            <div>
                                <h4 id="mezclador">Contenedores & Protectores</h4>
                                <ul>
                                    <li><a href="?pagina=productos">Contenedores hermeticos para valvulas</a></li>
                                    <li><a href="?pagina=productos">Protectores para manometros</a></li>
                                    <li><a href="?pagina=productos">Ver mas....</a></li>
                                </ul>
                            </div>

                        </div>
                        <!-- /submenu-interno -->
                    </div>
                    <!-- /submenu -->
                </li>

                <li>
                    <a href="#">Contactenos</a>
                    <div class="submenu">
                        <div class="submenu-interno">
                            <div id="div-contacto">

                                <p><img src="img/logo.png" alt="SSMGAS"/></p>
                                <h4>Información de contacto</h4>
                                <hr />
                                <article>
                                    Dirección Calle 145A # 45A-07 <br /> Bogotá D.C. Colombia <br />Telefonos : (+ 57-1) 258 4552 <br />(+ 57-1) 258 2629 <br/> Celular:(+ 57) 315 8040323 -<br /> (+ 57) 315 3091769<br />
                                    E-mail :ssmagdala@yahoo.com
                                </article>
                                <hr />
                                <input type="button" onclick="$(document).ready(function () { $(location).attr('href', '?pagina=contacto'); })" value="Enviar Solicitud" name="btnContacto" title="Enviar una solicitud">
                            </div>

                        </div>
                        <!-- /submenu-interno -->
                    </div>
                    <!-- /submenu -->
                </li>
            </ul>
        </nav>
        <!--/Barra de navegacion-->