    <header>
        <h1>Linea de contacto.</h1>
    </header>

    <div class="contenedor">
        <div class="form-contactenos">
            <form>
            	<input type="text" placeholder="Nombre de contacto" required="required" name="txtNombreContacto" class="txtContatenos">
            	
            	<input type="email" placeholder="Email" required="required" name="txtEmailContacto" class="txtContatenos">
            	
            	<p>Describa su solicitud</p>
            	<textarea rows="20" cols="60"></textarea>
            	<input type="button" value="Enviar" id="btnEnviarContacto" class="btnContactenos"/>
            </form>
        </div>
    </div>