
    <!-- Slider -->

    <div>

        <div id="da-slider" class="da-slider">
            <div class="da-slide">
                <h2>SSMGAS</h2>
                <p>Dedicados a la investigación y desarrollo continuo de nuevas tecnologias para cubrir sus necesidades con calidad.</p>
                <a href="?pagina=empresa" class="da-link">Ver mas</a>
                <div class="da-img">
                    <img src="img/img1.jpg" alt="image01" />
                </div>
            </div>
            <div class="da-slide">
                <h2>Linea de accesorios y<br />
                    mezcladores</h2>
                <p>Constantemente con nuestro esfuerzo y dedicación, logramos obtener las mas altas certficaciones en calidad y desarrollo del mercado.</p>
                <a href="?pagina=productos" class="da-link">Ver mas</a>
                <div class="da-img">
                    <img src="img/img8.jpg" alt="image01" />
                </div>
            </div>
            <div class="da-slide">
                <h2>Innovación & Desarrollo</h2>
                <p>El desarrollo de nuevas tecnologias al servicio del GNV & GLP.</p>
                <a href="?pagina=empresa" class="da-link">Ver mas</a>
                <div class="da-img">
                    <img src="img/img3.jpg" alt="image01" />
                </div>
            </div>
            <div class="da-slide">
                <h2>Control de calidad</h2>
                <p>Con las mas altas certificaciones internacionales de calidad, garantizamos un producto en sus manos de la mas alta calidad.</p>
                <a href="?pagina=empresa" class="da-link">Ver mas</a>
                <div class="da-img">
                    <img src="img/img4.jpg" alt="image01" />
                </div>
            </div>
             <div class="da-slide">
                <h2>Control de calidad</h2>
                <p>Con las mas altas certificaciones internacionales de calidad, garantizamos un producto en sus manos de la mas alta calidad.</p>
                <a href="?pagina=mezcladores" class="da-link">Ver mas</a>
                <div class="da-img">
                    <img src="img/img6.jpg" alt="image01" />
                </div>
            </div>
             
            <nav class="da-arrows">
                <span class="da-arrows-prev"></span>
                <span class="da-arrows-next"></span>
            </nav>
        </div>
    </div>

    <!--/Slider-->


    <!-- Portfolio Section -->
    <div class="contenedor">
        <div>
            <h2 class="encabezado">Nuestros Productos</h2>
        </div>
        <div class="cont-interno-default">
            <div class="producto-img">
                <div class="img-portafolio">
                    <a href="?pagina=productos">
                        <img src="img/TEE Porta Manómetro.jpg" alt="Boquilla GNV">
                    </a>
                </div>
                <div class="desc-img-producto">
                    <q>Ref: 1438</q>
                    <p><strong>TEE Porta Manómetro</strong></p>
                </div>
            </div>
            <div class="producto-img">
                <div class="img-portafolio">
                    <a href="?pagina=productos">
                        <img src="img/ssmagdala 035.JPG" alt="Grapa para ruta">
                    </a>
                </div>
                <div class="desc-img-producto">
                    <q>Ref: 1438</q>
                    <p><strong>Boquilla GNV</strong></p>
                </div>
            </div>
            <div class="producto-img">
                <div class="img-portafolio">
                    <a href="?pagina=productos">
                        <img src="img/Tapón para Contenedor.JPG" alt="Tee 3 vias">
                    </a>
                    <div class="desc-img-producto">
                        <q>Ref: 1438</q>
                        <p><strong>Tapón para Contenedor</strong></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="cont-interno-default">
            <div class="producto-img">
                <div class="img-portafolio">
                    <a href="?pagina=productos">
                        <img src="img/Tee para empalme de cilindros.JPG" alt="Boquilla GNV">
                    </a>
                </div>
                <div class="desc-img-producto">
                    <q>Ref: 1438</q>
                    <p><strong>Tee para empalme de cilindros</strong></p>
                </div>
            </div>
            <div class="producto-img">
                <div class="img-portafolio">
                    <a href="?pagina=productos">
                        <img src="img/Tee Aluminio Aguas.JPG" alt="Grapa para ruta">
                    </a>
                </div>
                <div class="desc-img-producto">
                    <q>Ref: 1438</q>
                    <p><strong>Tee Aluminio Aguas</strong></p>
                </div>
            </div>
            <div class="producto-img">
                <div class="img-portafolio">
                    <a href="?pagina=productos">
                        <img src="img/20141CONTENEDOR HERMETICO TIPO C.jpg" alt="Tee 3 vias">
                    </a>
                    <div class="desc-img-producto">
                        <q>Ref: 1438</q>
                        <p><strong>Contenedor Hermetico</strong></p>
                    </div>
                </div>
            </div>
        </div>
    
    <!--Portafolio Section-->

    <!-- Seccion de descipcion -->
    <div class="cont-descripcion-default">
        <div>
            <h2 class="encabezado">Una empresa dedicada al desarrollo de nuevas tecnologias para el bienestar de todos.</h2>
        </div>
        <div class="descripcion">
            <h4>Respaldo & Experiencia:</h4>
            <ul>
                <li><strong>Certificación de calidad Beru Veritas</strong>
                </li>
                <li>Contenedor Hermetico de Vienteo
                    <ul>
                        <li>Tipo A</li>
                        <li>Tipo B</li>
                        <li>Tipo C</li>
                    </ul>
                </li>
                <li>Mezcladores Gas/Aire</li>
                <li>Accesorios de conexion de alta presion para GNVC</li>
                <li>Ajustador de flujo de gas</li>
            </ul>
            <p>
                <strong>Pedreros Orozco Y Cia.</strong> comprometidos con la satisfacción de nuestros clientes se esmera cada día para seguir fortacilendo nuestro 
                sistema de calidad y poder birndar las mejores partes para su motor bajo los más altos estandares de calidad internacional, ayudando asi a la conservacion del medio ambiente con un consume de combustible efeciente y amigable con el medio ambiente.
            </p>
        </div>
        <div class="descripcion">
            <img class="img-descripcion" src="img/img5.jpg" alt="">
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Formulario de envio de E-mail de contacto -->
    <div class="contactenos">
        <div>
            <div class="form-contactenos">
                <p>Dejanos tu E-mail y te contactaremos para resolver tus inquietudes.</p>

                <input type="text" placeholder="E-mail" required="required" id="txtEmailInicio" class="txtContatenos"/>
                <div>
                    <input type="button" value="Enviar" name="btnEnviarInicio" id="btnEnviarInicio" class="txtContatenos"/>
                </div>
            </div>

        </div>
    </div>
</div>
    <hr>